# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './quick_renet.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import ctypes
import subprocess
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
import psutil
from PyQt5.QtCore import QStringListModel
from PyQt5.QtWidgets import QMessageBox


class Ui_Dialog(object):

    def get_network_list(self):
        networks = []
        for k in psutil.net_if_addrs():
            networks.append(k)
        return networks

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(345, 262)
        self.select = ""
        slm = QStringListModel();
        self.network_list = self.get_network_list()
        slm.setStringList(self.network_list)
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(10, 10, 321, 192))
        self.listView.setObjectName("网络列表")
        self.listView.setModel(slm)

        self.listView.clicked.connect(self.set_select)

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(230, 210, 101, 41))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(self.save_network)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "快速网络重启-初始设置  by-Rui v1.0"))
        self.pushButton.setText(_translate("Dialog", "保存设置"))

    def save_network(self):
        file = open(".Selected", "w+", encoding="utf8")
        if self.select != "":
            try:
                network = self.network_list[self.select]
                file.write(str(network))
                print("已选择网卡：",network,",关闭并重新运行程序以重启网卡.")
            finally:
                file.close()
        else:
            QtWidgets.QMessageBox.information(self, "错误", "未选择数据 ")
            return 0




    def set_select(self,qModelIndex):
        self.select = int(qModelIndex.row())

